# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-01 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20190129_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='category',
            name='views',
            field=models.IntegerField(default='0'),
        ),
    ]
